#+STARTUP: hidestars
#+TITLE:Hacky Lisp

Common Lisp has a lot of simplicity in it, but there are some parts of
the language that are incredibly complex... Functions that can be used
to hack out a ton of functionality really quickly.

Two examples of this are =format= function and the =loop= macro.

* format
=format= is a function that allows you to output a formatted string
from pretty much anything.

=format= accepts a minimum of 2 arguments, the first being where the
string would be output, passing in =t= will output the string to
standard output and return =nil=, having the second parameter as =nil=
will output the string as the result of the function. Any other values
for the function will output the string to that place as if it were a
stream or a string with a thing called a "fill pointer".

The second parameter is the "control string", which supports eons of
directives to output your textual data in pretty much any way
possible.

#+BEGIN_SRC lisp :export both
  (format nil "|键吵夯蹭峻祜镳骘躔麸构泔祆邈┅＋盼倪右＋遗诱淘雍＋忮玳钸屮犴痨卑北辈背贝钡倍狈备惫舶脖膊渤泊驳捕卜哺补嘲潮巢吵炒车扯撤掣彻窗幢床闯创吹炊捶锤垂蛋当挡党荡档刀捣蹈倒栋侗恫冻洞兜抖斗陡豆钒繁凡烦反返范贩犯饭赴副覆赋复傅付阜父腹拱贡共钩勾沟苟狗垢构＋孱溥屮犴痨